# Generated by Django 2.1.3 on 2019-01-25 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contact_doc',
        ),
    ]
